### ISSUE TITLE
A New Connection.

### ISSUE THREAD

**Issue by aguluman** [Breathe-of-fate/python_learning_hyperskills#1]
Hi there i would like to connect with you on any social media platform of your choice.

**Comment by Breathe-of-fate** [comment]
Hi,You can reach me in ***@***.***_of_fate01:04, 7 января 2024 г., Chukwuma Akunyili ***@***.***>:
Hi there i would like to connect with you on any social media platform of your choice.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by aguluman** [comment]
My apologies, I did not understand what you sent. I saw your comment on the HyperSkill platform, on the hash table(collision) problem you solved a while back. And I decided to reach out. 
Hope it's not a problem.
